version: "3.6"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
 
  organizr:
    container_name: organizr
    restart: always
    image: lsiocommunity/organizr
    volumes:
      - ${USERDIR}/docker/organizr:/config
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "80:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

  plexms:
    container_name: plex
    restart: always
    image: plexinc/pms-docker:${PMSTAG}
#    network_mode: 'host'
    hostname: ${HOSTNAME}
    volumes:
      - ${USERDIR}/docker/plexms:/config
      - ${USERDIR}/Downloads/plex_tmp:/transcode
      - /mnt/music:/media/music
      - /mnt/video:/media/video
      - /mnt/photo:/media/photo
      - ${USERDIR}/docker/shared:/shared
    ports:
      - '${IP_ADDRESS}:32400:32400/tcp'
      - '${IP_ADDRESS}:3005:3005/tcp'
      - '${IP_ADDRESS}:8324:8324/tcp'
      - '${IP_ADDRESS}:32469:32469/tcp'
      - '${IP_ADDRESS}:1900:1900/udp'
      - '${IP_ADDRESS}:32410:32410/udp'
      - '${IP_ADDRESS}:32412:32412/udp'
      - '${IP_ADDRESS}:32413:32413/udp'
      - '${IP_ADDRESS}:32414:32414/udp'
    environment:
      - PLEX_CLAIM=${PMSTOKEN}
      - ADVERTISE_IP=http://${IP_ADDRESS}:32400/
      #- ALLOWED_NETWORKS=${CIDR_ADDRESS}
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}

  tautulli:
    container_name: tautulli
    restart: always
    image: linuxserver/tautulli
    volumes:
      - ${USERDIR}/docker/tautulli/config:/config
      - ${USERDIR}/docker/tautulli/logs:/logs:ro
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "${IP_ADDRESS}:8181:8181"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}  
    depends_on:
      - plexms

    # ----------------------------------------
    # OMBI
    # Request Service for Plex Content
    # ----------------------------------------
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: always
    ports:
        - '${IP_ADDRESS}:3579:3579'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - VIRTUAL_HOST=request.${DOMAIN}
        - LETSENCRYPT_HOST=request.${DOMAIN}
        - LETSENCRYPT_EMAIL=${EMAIL}
    volumes:
        - ${USERDIR}/docker/ombi:/config
        - ${USERDIR}/docker/shared:/shared
